apiVersion: k0sctl.k0sproject.io/v1beta1
kind: Cluster
metadata:
  name: k0s-cluster
spec:
  hosts:
  - hostname: k0s-1.lan
    role: controller+worker
    noTaints: true
    os: debian
    environment: {}
    privateInterface: eth1
    privateAddress: 10.100.10.101
    ssh:
      address: 192.168.1.61
      user: root
      port: 22
      keyPath: ~/.ssh/id_rsa
  - hostname: k0s-2.lan
    role: worker
    os: debian
    privateInterface: eth1
    privateAddress: 10.100.10.102
    ssh:
      address: 192.168.1.62
      user: root
      port: 22
      keyPath: ~/.ssh/id_rsa
  - hostname: k0s-3.lan
    role: worker
    os: debian
    privateInterface: eth1
    privateAddress: 10.100.10.103
    ssh:
      address: 192.168.1.63
      user: root
      port: 22
      keyPath: ~/.ssh/id_rsa
  k0s:
    version: v1.29.2+k0s.0
    versionChannel: stable
    dynamicConfig: false
    config:
      apiVersion: k0s.k0sproject.io/v1beta1
      kind: Cluster
      metadata:
        name: k0s-dev
      spec:
        api:
          address: 10.100.10.101
          k0sApiPort: 9443
          port: 6443
          sans:
            - 10.100.10.101
        installConfig:
          users:
            etcdUser: etcd
            kineUser: kube-apiserver
            konnectivityUser: konnectivity-server
            kubeAPIserverUser: kube-apiserver
            kubeSchedulerUser: kube-scheduler
        konnectivity:
          adminPort: 8133
          agentPort: 8132
        network:
          provider: kuberouter
          podCIDR: 10.0.0.0/16
          serviceCIDR: 10.1.0.0/16
          kubeProxy:
            disabled: false
            mode: iptables
          kuberouter:
            autoMTU: true
            mtu: 0
            peerRouterASNs: ""
            peerRouterIPs: ""
        podSecurityPolicy:
          defaultPolicy: 00-k0s-privileged
        storage:
          type: etcd
        telemetry:
          enabled: true
    # config:
    #   spec:
    #     network:
    #       provider: calico
    #       nodeLocalLoadBalancing:
    #         enabled: true
    #         type: EnvoyProxy
    #     telemetry:
    #       enabled: false
